"""Placeholder logo generator — Obscurity-Is-Dead.

AI-authored (Claude, 2026-05-02). Rule-1 / Rule-14 compliance:
this script and its outputs (`logo-obscurity-is-dead.png`,
`logo-pandora-jar-intact.png`) are placeholder assets.

The author intends to replace these with Google-Gemini-generated
artwork (the shattered- and intact-Pandora-jar visuals described in
section 9.0 / 10 of the paper). Until the Gemini assets are dropped
in by the researcher, this script renders typographic placeholders
so that:

  * `make pdf` succeeds end-to-end and the layout-scrutinizer stage
    can run against `paper/main.pdf`;
  * the placeholder identity is *visible* in the rendered PDF — no
    silent stand-in (Rule 1);
  * the prose claim that these files exist under `paper/figures/`
    becomes true (Rule 1);
  * regeneration is reproducible (Rule 14).

Run with:
    python paper/figures/logo-placeholders.py

Outputs are written next to this script.
"""
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

OUT_DIR = Path(__file__).resolve().parent


def render_placeholder(filename: str, headline: str, motif: str) -> None:
    fig, ax = plt.subplots(figsize=(6.0, 6.0), dpi=200)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_axis_off()

    ax.add_patch(
        FancyBboxPatch(
            (0.04, 0.04),
            0.92,
            0.92,
            boxstyle="round,pad=0.02,rounding_size=0.04",
            linewidth=2.0,
            edgecolor="#222222",
            facecolor="#f6f4ee",
        )
    )

    ax.text(
        0.5,
        0.82,
        "PLACEHOLDER",
        ha="center",
        va="center",
        fontsize=22,
        weight="bold",
        color="#a02020",
    )
    ax.text(
        0.5,
        0.74,
        "(awaiting Google-Gemini-generated final asset)",
        ha="center",
        va="center",
        fontsize=10,
        style="italic",
        color="#444444",
    )

    ax.text(
        0.5,
        0.56,
        headline,
        ha="center",
        va="center",
        fontsize=15,
        weight="bold",
        color="#222222",
        wrap=True,
    )
    ax.text(
        0.5,
        0.42,
        motif,
        ha="center",
        va="center",
        fontsize=11,
        color="#222222",
        wrap=True,
    )

    ax.text(
        0.5,
        0.16,
        "Generated by paper/figures/logo-placeholders.py",
        ha="center",
        va="center",
        fontsize=8,
        color="#666666",
    )
    ax.text(
        0.5,
        0.11,
        "AI-authored placeholder (Claude, 2026-05-02)",
        ha="center",
        va="center",
        fontsize=8,
        color="#666666",
    )

    fig.savefig(OUT_DIR / filename, dpi=200, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)


def main() -> None:
    render_placeholder(
        "logo-obscurity-is-dead.png",
        "Obscurity Is Dead\nProprietary by Design.  Open by AI.",
        "Motif: shattered Pandora jar (front-matter project logo).",
    )
    render_placeholder(
        "logo-pandora-jar-intact.png",
        "The Pandora Moment",
        "Motif: intact Pandora jar with Hope still under its rim\n"
        "(Hesiod, Works and Days, ll. 96-98).",
    )


if __name__ == "__main__":
    main()
