#!/usr/bin/env python3
"""Modeler agent (stage 7) implementation -- emit `docs/provenance.ttl`.

The Modeler agent prompt at `docs/prompts/modeler-prompt.md` defines the
spec; this script is the executable implementation of that spec.  It
reads:

    docs/sources.md          - L-* and S-* entries with verification status
    docs/logbook.md          - pipeline-stage run instances + builds
    paper/figures/README.md  - figure registry (rule 15)

and emits a W3C PROV-O Turtle graph at `docs/provenance.ttl` covering
every modellable relationship the prose asserts.  Bootstrap claim
inventory + commits + agents are kept as static seeds; the dynamic part
(sources, run instances) is regenerated each pass.

Rule 1: never invents triples.  Every entry corresponds to a parseable
line in the named input file.

Rule 13: refuses to write the file if any literal matches a known
live-credential pattern.

Rule 14: writes locally only; never deploys.
"""

from __future__ import annotations

import datetime as dt
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCES_MD = REPO / "docs" / "sources.md"
LOGBOOK_MD = REPO / "docs" / "logbook.md"
TTL_OUT = REPO / "docs" / "provenance.ttl"

LIVE_CREDENTIAL_PATTERNS = [
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}"),
    re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"),
    re.compile(r"ghp_[A-Za-z0-9]{30,}"),
]

LADDER_RUNGS = {
    "[unverified-external]":   "oid:unverified-external",
    "[needs-research]":        "oid:needs-research",
    "[lit-retrieved]":         "oid:lit-retrieved",
    "[ai-confirmed]":          "oid:ai-confirmed",
    "[lit-read]":              "oid:lit-read",
    "[repo-vendored]":         "oid:repo-vendored",
    "[repo-referenced]":       "oid:repo-referenced",
}


def parse_sources(md: str):
    l_re = re.compile(r"^- \*\*(L-[A-Z]+-[0-9]+)\*\*\s+(.+?)$", re.M)
    for m in l_re.finditer(md):
        ident, rest = m.group(1), m.group(2)
        title_match = re.match(r"\[([^\]]+)\]", rest)
        title = title_match.group(1) if title_match else rest[:120]
        rung = "oid:lit-retrieved"
        if "[lit-read]" in rest:
            rung = "oid:lit-read"
        elif "[ai-confirmed]" in rest:
            rung = "oid:ai-confirmed"
        elif "[unverified-external]" in rest:
            rung = "oid:unverified-external"
        edge = "[edge-case" in rest
        yield ("L", ident, title, rung, edge)

    sections = re.split(r"^### ", md, flags=re.M)
    for section in sections:
        m = re.match(r"(S-[A-Z0-9]+-[0-9]+)\s*[-—]+\s*([^\n]+)", section)
        if not m:
            continue
        ident, title = m.group(1), m.group(2)
        rung = "oid:repo-referenced"
        for tag, rung_uri in LADDER_RUNGS.items():
            if tag in section:
                rung = rung_uri
                if tag == "[repo-vendored]":
                    break
        yield ("S", ident, title, rung, False)


def parse_logbook_runs(md: str):
    h_re = re.compile(r"^### (\d{4}-\d{2}-\d{2})\s*\(([^)]+)\)", re.M)
    for m in h_re.finditer(md):
        yield (m.group(1), m.group(2).strip())


def ttl_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", " ")


PRELUDE_TMPL = """\
# docs/provenance.ttl - Obscurity-Is-Dead PROV-O graph
#
# Generated {ts} by the Modeler agent (stage 7).
# Source: scripts/build_provenance_graph.py + docs/prompts/modeler-prompt.md
# Input commit: {sha}
#
# DO NOT EDIT BY HAND - regenerated by `scripts/build_provenance_graph.py`.
# Manual edits will be overwritten on the next pass; route corrections via
# the Aligner hand-back instead.
#
# Coverage in this pass: {coverage_summary}
# See docs/handbacks/modeler-report.md for per-pass deltas + integrity-query results.

@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix oid:  <https://github.com/noheton/obscurity-is-dead/ns#> .
@prefix dct:  <http://purl.org/dc/terms/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

oid:Claim                  rdfs:subClassOf prov:Entity .
oid:Source                 rdfs:subClassOf prov:Entity .
oid:Transcript             rdfs:subClassOf prov:Entity .
oid:Figure                 rdfs:subClassOf prov:Entity .
oid:Commit                 rdfs:subClassOf prov:Entity .
oid:VerificationStatus     rdfs:subClassOf prov:Entity .
oid:PipelineStage          rdfs:subClassOf prov:Activity .
oid:Build                  rdfs:subClassOf prov:Activity .
oid:AIAgent                rdfs:subClassOf prov:Agent .
oid:HumanResearcher        rdfs:subClassOf prov:Agent .

# Verification-status individuals (rule 18 ladder)
oid:unverified-external a oid:VerificationStatus ; dct:title "[unverified-external]" .
oid:needs-research      a oid:VerificationStatus ; dct:title "[needs-research]" .
oid:lit-retrieved       a oid:VerificationStatus ; dct:title "[lit-retrieved]" .
oid:ai-confirmed        a oid:VerificationStatus ; dct:title "[ai-confirmed]" .
oid:lit-read            a oid:VerificationStatus ; dct:title "[lit-read]" .
oid:repo-vendored       a oid:VerificationStatus ; dct:title "[repo-vendored]" .
oid:repo-referenced     a oid:VerificationStatus ; dct:title "[repo-referenced]" .

# Agents
oid:florian-krebs a prov:Agent, oid:HumanResearcher, foaf:Person ;
  foaf:name "Florian Krebs" ;
  oid:orcid "0000-0001-6033-801X" ;
  oid:capacity "Independent researcher (personal capacity)" .

oid:claude-opus-4-7 a prov:Agent, oid:AIAgent ;
  dct:title "Claude Opus 4.7 (1M context)" ;
  oid:modelId "claude-opus-4-7" ;
  oid:harness "claude-code-cli" .

oid:gemini a prov:Agent, oid:AIAgent ;
  dct:title "Google Gemini" ;
  oid:harness "gemini.google.com (web)" .

# Pipeline-stage definitions (CLAUDE.md Agent workflow)
oid:stage-orchestrator           a oid:PipelineStage ; dct:title "Orchestrator (Stage 0)" ;            oid:promptFile "docs/prompts/orchestrator-prompt.md" .
oid:stage-research               a oid:PipelineStage ; dct:title "Research Protocol (Stage 1)" ;       oid:promptFile "docs/prompts/research-protocol-prompt.md" .
oid:stage-source-analyzer        a oid:PipelineStage ; dct:title "Source Analyzer (Stage 1.5)" ;       oid:promptFile "docs/prompts/source-analyzer-prompt.md" .
oid:stage-writer                 a oid:PipelineStage ; dct:title "Scientific Writer (Stage 2)" ;       oid:promptFile "docs/prompts/scientific-writer-prompt.md" .
oid:stage-illustrator            a oid:PipelineStage ; dct:title "Illustration (Stage 3)" ;            oid:promptFile "docs/prompts/illustration-prompt.md" .
oid:stage-layout-scrutinizer     a oid:PipelineStage ; dct:title "Layout Scrutinizer (Stage 4)" ;      oid:promptFile "docs/prompts/layout-scrutinizer-prompt.md" .
oid:stage-readability-scrutinizer a oid:PipelineStage ; dct:title "Readability & Novelty Scrutinizer (Stage 5)" ; oid:promptFile "docs/prompts/readability-novelty-prompt.md" .
oid:stage-aligner                a oid:PipelineStage ; dct:title "Aligner (Stage 6)" ;                 oid:promptFile "docs/prompts/aligner-prompt.md" .
oid:stage-modeler                a oid:PipelineStage ; dct:title "Modeler (Stage 7)" ;                 oid:promptFile "docs/prompts/modeler-prompt.md" .

# Named commits referenced inline in paper / logbook
oid:commit-ffdf60c a oid:Commit ; dct:identifier "ffdf60c" ; dct:description "feat(experiments): embed vendor repos as plain files for agent access." .
oid:commit-668fa8d a oid:Commit ; dct:identifier "668fa8d" ; dct:description "Aligner round 1 closure (ALN-01..ALN-13)." .
oid:commit-a543917 a oid:Commit ; dct:identifier "a543917" ; dct:description "Aligner round 2 dispatch." .
oid:commit-8398ae0 a oid:Commit ; dct:identifier "8398ae0" ; dct:description "Writer pass closing all ten round-2 routed entries." .
oid:commit-c4a1fdf a oid:Commit ; dct:identifier "c4a1fdf" ; dct:description "Aligner round 3: RE-ALIGNMENT REQUIRED: no." .
oid:commit-302bf96 a oid:Commit ; dct:identifier "302bf96" ; dct:description "Pandora-jar-intact final asset (Q11 closure)." .
oid:commit-5ddd3fc a oid:Commit ; dct:identifier "5ddd3fc" ; dct:description "Q12: papermill commentary + Modeler agent + bootstrap PROV-O graph." .
oid:commit-5495888 a oid:Commit ; dct:identifier "5495888" ; dct:description "Q12 build: make all clean rebuild + Q12 Build entity in PROV-O graph." .
oid:commit-923c985 a oid:Commit ; dct:identifier "923c985" ; dct:description "Q13: browser-viewable PROV-O graph site (local artifact, rule-14 governed)." .

# Builds (recorded in logbook)
oid:build-2026-05-04-Q10 a oid:Build ;
  dct:date "2026-05-04"^^xsd:date ;
  rdfs:label "Q10 build (post-Aligner-round-3)" ;
  prov:wasAssociatedWith oid:florian-krebs ;
  prov:used oid:commit-c4a1fdf ;
  prov:generated oid:pdf-main-Q10 , oid:pdf-condensed-Q10 .

oid:pdf-main-Q10 a prov:Entity ;
  dct:title "paper/main.pdf (Q10 build)" ;
  oid:pageCount "59"^^xsd:integer ;
  oid:byteSize "3069752"^^xsd:integer ;
  oid:sha256 "39878cf8e77c3c39e0238e70cb0046471511ae682f6b1ff155064e08df0e8f2c" .

oid:pdf-condensed-Q10 a prov:Entity ;
  dct:title "paper/main-condensed.pdf (Q10 build)" ;
  oid:pageCount "9"^^xsd:integer ;
  oid:byteSize "580151"^^xsd:integer ;
  oid:sha256 "565de09dad73d4af7e4d170a69479e8f9e4f57be804ab4e23e7b11dde9b17237" .

oid:build-2026-05-04-Q12 a oid:Build ;
  dct:date "2026-05-04"^^xsd:date ;
  rdfs:label "Q12 build (post-Author's-Note + Modeler agent + bootstrap PROV-O graph)" ;
  prov:wasAssociatedWith oid:florian-krebs , oid:claude-opus-4-7 ;
  prov:wasInformedBy oid:writer-pass-2026-05-04-papermill ;
  prov:generated oid:pdf-main-Q12 , oid:pdf-condensed-Q12 .

oid:pdf-main-Q12 a prov:Entity ;
  dct:title "paper/main.pdf (Q12 build)" ;
  oid:pageCount "60"^^xsd:integer ;
  oid:byteSize "3073523"^^xsd:integer ;
  oid:sha256 "dea0963c6642efa0b688dcd0c4c0f098f0a4676c8f7ded232b69dae33f3fa5f5" .

oid:pdf-condensed-Q12 a prov:Entity ;
  dct:title "paper/main-condensed.pdf (Q12 build)" ;
  oid:pageCount "9"^^xsd:integer ;
  oid:byteSize "580153"^^xsd:integer ;
  oid:sha256 "c0598eb1aafbe2b0cba9eb7799e3aba6f01a6c8b90cee9ae83f653257168c9ea" .

oid:writer-pass-2026-05-04-papermill a oid:PipelineStage ;
  rdfs:label "Writer pass: papermill commentary + PROV-O modeler agent (2026-05-04)" ;
  prov:wasAssociatedWith oid:claude-opus-4-7 , oid:florian-krebs ;
  prov:startedAtTime "2026-05-04T00:00:00Z"^^xsd:dateTime ;
  oid:promptFile "docs/prompts/scientific-writer-prompt.md" ;
  oid:branch "claude/add-papermill-commentary-ufAr0" .

oid:source-analyzer-2026-05-02 a oid:PipelineStage ;
  rdfs:label "Source Analyzer pass: 114 entries upgraded to [ai-confirmed]" ;
  prov:wasAssociatedWith oid:claude-opus-4-7 , oid:florian-krebs ;
  prov:startedAtTime "2026-05-02T00:00:00Z"^^xsd:dateTime ;
  oid:promptFile "docs/prompts/source-analyzer-prompt.md" .
"""


CORE_CLAIMS_BLOCK = """

# =====================================================================
# Selected load-bearing claims (long-form + condensed)
# =====================================================================

oid:claim-authors-note-tokens-out-tokens-in a oid:Claim ;
  dct:source "paper/main.md#authors-note-tokens-out-tokens-in" ;
  dct:description "The strange shape of scientific debate: papers as transient token checkpoints between AI agents; provenance graph as structural answer." ;
  prov:wasGeneratedBy oid:writer-pass-2026-05-04-papermill ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "first-person-reflection" ;
  oid:condensedOnly false .

oid:claim-23-provenance-modeler a oid:Claim ;
  dct:source "paper/main.md#sec-provenance-mapping" ;
  dct:description "Provenance information is rendered as a machine-readable W3C PROV-O graph by the Modeler agent (stage 7)." ;
  prov:wasGeneratedBy oid:writer-pass-2026-05-04-papermill ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "first-person-methodology" ;
  oid:condensedOnly false .

oid:claim-77-sloppification-base-rate a oid:Claim ;
  dct:source "paper/main.md#sec-sloppification" ;
  dct:description "Empirical fabricated-citation base rates 18-55%; paper-mill flood at NHANES scale (190 papers in 10 months 2024)." ;
  prov:wasDerivedFrom oid:source-L-SLOP-1 , oid:source-L-SLOP-2 , oid:source-L-SLOP-8 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "[ai-confirmed]" ;
  oid:condensedOnly false .

oid:claim-77-model-collapse a oid:Claim ;
  dct:source "paper/main.md#sec-model-collapse" ;
  dct:description "Recursive AI-on-AI training collapses the tail of the distribution; mitigation is mixing rather than replacing." ;
  prov:wasDerivedFrom oid:source-L-MC-1 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "[lit-read]" ;
  oid:condensedOnly false .

oid:claim-1-effort-gap-software a oid:Claim ;
  dct:source "paper/main.md#sec-introduction-effort-gap" ;
  dct:description "Software-side effort-gap collapse: 24.4% cognitive-burden reduction (DeGPT)." ;
  prov:wasDerivedFrom oid:source-L-RE-2 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "[ai-confirmed]" ;
  oid:condensedOnly false .

oid:claim-1-effort-gap-recodec a oid:Claim ;
  dct:source "paper/main.md#sec-introduction-effort-gap" ;
  dct:description "31% to 53% correct-solve-rate uplift on RE tasks (with p=0.189 caveat preserved)." ;
  prov:wasDerivedFrom oid:source-L-RE-3 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "[ai-confirmed]" ;
  oid:condensedOnly false .

oid:claim-1-effort-gap-llm4decompile a oid:Claim ;
  dct:source "paper/main.md#sec-introduction-effort-gap" ;
  dct:description ">100% improvement in re-executability for AI-assisted code synthesis." ;
  prov:wasDerivedFrom oid:source-L-RE-1 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "[ai-confirmed]" ;
  oid:condensedOnly false .

oid:claim-3-spider-farmer-effort-gap a oid:Claim ;
  dct:source "paper/main.md#sec-spider-farmer-kpi" ;
  dct:description "Spider Farmer integration: ~10.5 h AI-assisted vs 60-120 h manual baseline." ;
  prov:wasDerivedFrom oid:source-S-SF-1 , oid:source-S-SF-2 , oid:source-S-SF-3 , oid:source-S-SF-4 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "case-study-direct-measurement" ;
  oid:condensedOnly false .

oid:claim-4-ecoflow-attack-surface a oid:Claim ;
  dct:source "paper/main.md#sec-ecoflow-security" ;
  dct:description "Three-surface reconciliation produced local-control integration AND surfaced a previously undocumented attack surface (redaction-policy enumerated)." ;
  prov:wasDerivedFrom oid:source-S-EF-1 , oid:source-S-EF-2 , oid:source-S-EF-4 , oid:source-S-EF-6 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "case-study-direct-measurement" ;
  oid:condensedOnly false .

oid:claim-7-mythos-asymmetry-narrowing a oid:Claim ;
  dct:source "paper/main.md#sec-disc-asymmetry" ;
  dct:description "Project Glasswing / Claude Mythos Preview: defender-favouring asymmetry persists but narrows; horizon shorter than original framing." ;
  prov:wasDerivedFrom oid:source-L-MYTHOS-1 , oid:source-L-MYTHOS-2 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "[ai-confirmed]" ;
  oid:condensedOnly false .

oid:claim-cond-ladder a oid:Claim ;
  dct:source "paper/main-condensed.md#sec-3-method" ;
  dct:description "Verification-status ladder: [unverified-external] -> [needs-research] -> [lit-retrieved] -> [ai-confirmed] -> [lit-read]." ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "methodology-self-description" ;
  oid:condensedOnly true .

oid:claim-cond-eight-practices a oid:Claim ;
  dct:source "paper/main-condensed.md#sec-4-discussion" ;
  dct:description "Eight integrated practices spanning transcript preservation through FAIR alignment." ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "methodology-self-description" ;
  oid:condensedOnly true .

oid:claim-cond-fair4ai a oid:Claim ;
  dct:source "paper/main-condensed.md#sec-4-discussion" ;
  dct:description "FAIR4AI extension proposal: F/A/I/R mapped to AI-mediated research processes." ;
  prov:wasDerivedFrom oid:source-L-FAIR-1 , oid:source-L-FAIR-2 , oid:source-L-FAIR-3 ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 ;
  oid:invocationFloor "[ai-confirmed]" ;
  oid:condensedOnly true .
"""


FIGURES_BLOCK = """

# =====================================================================
# Figures (rule 15: data + script binding or oid:externallyGenerated)
# =====================================================================

oid:figure-fig1-effort-gap a oid:Figure ;
  dct:source "paper/figures/fig1-effort-gap.svg" ;
  prov:wasDerivedFrom <paper/figures/data/effort-gap.csv> ;
  prov:wasGeneratedBy <paper/figures/fig1-effort-gap.py> ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 .

oid:figure-fig5-methodology a oid:Figure ;
  dct:source "paper/figures/fig5-methodology.svg" ;
  prov:wasGeneratedBy <paper/figures/fig5-methodology.py> ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 .

oid:figure-fig9-verification-pipeline a oid:Figure ;
  dct:source "paper/figures/fig9-verification-pipeline.svg" ;
  prov:wasGeneratedBy <paper/figures/fig9-verification-pipeline.py> ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 .

oid:figure-fig11-eight-practices a oid:Figure ;
  dct:source "paper/figures/fig11-eight-practices.svg" ;
  prov:wasGeneratedBy <paper/figures/fig11-eight-practices.py> ;
  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7 .

oid:figure-logo-pandora-shattered a oid:Figure ;
  dct:source "paper/figures/logo-pandora-jar-shattered.png" ;
  oid:externallyGenerated true ;
  prov:wasAttributedTo oid:gemini , oid:florian-krebs .

oid:figure-logo-pandora-intact a oid:Figure ;
  dct:source "paper/figures/logo-pandora-jar-intact.png" ;
  oid:externallyGenerated true ;
  prov:wasGeneratedBy oid:commit-302bf96 ;
  prov:wasAttributedTo oid:gemini , oid:florian-krebs .
"""


def emit_pipeline_runs(runs):
    out = ["", "# =====================================================================",
           "# Pipeline-stage run instances (parsed from docs/logbook.md)",
           "# ====================================================================="]
    seen = set()
    for date, label in runs:
        slug = re.sub(r"[^a-zA-Z0-9]+", "-", label.lower()).strip("-")[:60]
        if not slug:
            continue
        node = f"oid:run-{date}-{slug}"
        if node in seen:
            node = f"{node}-{len(seen):03d}"
        seen.add(node)
        out.append(
            f'{node} a oid:PipelineStage ;\n'
            f'  rdfs:label "{ttl_escape(date + " - " + label)}" ;\n'
            f'  prov:startedAtTime "{date}T00:00:00Z"^^xsd:dateTime ;\n'
            f'  prov:wasAssociatedWith oid:claude-opus-4-7 , oid:florian-krebs .'
        )
    return "\n".join(out)


def emit_sources(sources):
    out = ["", "# =====================================================================",
           "# Sources (parsed from docs/sources.md; rule-18 traceability spine)",
           "# ====================================================================="]
    for kind, ident, title, rung, edge in sources:
        node = f"oid:source-{ident}"
        title_clean = ttl_escape(title.strip())
        triples = [
            f'  dct:identifier "{ident}"',
            f'  dct:title "{title_clean}"',
            f'  oid:hasVerificationStatus {rung}',
            f'  prov:wasAttributedTo oid:florian-krebs , oid:claude-opus-4-7',
        ]
        if rung == "oid:ai-confirmed":
            triples.append('  prov:wasGeneratedBy oid:source-analyzer-2026-05-02')
        if edge:
            triples.append('  oid:edgeCase true')
        if kind == "S":
            triples.append('  oid:sourceKind "code-side"')
        else:
            triples.append('  oid:sourceKind "literature"')
        out.append(f"{node} a oid:Source ;\n" + " ;\n".join(triples) + " .")
    return "\n".join(out)


def check_rule_13(text: str):
    leaks = []
    for pat in LIVE_CREDENTIAL_PATTERNS:
        for m in pat.finditer(text):
            leaks.append((pat.pattern, m.group(0)[:40]))
    if leaks:
        print("RULE-13 GUARD: refusing to write graph; live-credential patterns matched.",
              file=sys.stderr)
        for p, sample in leaks:
            print(f"  pattern {p!r} matched at sample {sample!r}", file=sys.stderr)
        sys.exit(2)


def main() -> int:
    src_md = SOURCES_MD.read_text()
    log_md = LOGBOOK_MD.read_text()
    sources = list(parse_sources(src_md))
    runs = list(parse_logbook_runs(log_md))
    sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                         capture_output=True, text=True, cwd=REPO).stdout.strip() or "(no-git)"
    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    summary = (f"{len(sources)} sources (L-* + S-*), "
               f"{len(runs)} pipeline-run instances, "
               f"13 load-bearing claims, 6 figures.")
    parts = [PRELUDE_TMPL.format(ts=ts, sha=sha, coverage_summary=summary)]
    parts.append(emit_pipeline_runs(runs))
    parts.append(emit_sources(sources))
    parts.append(CORE_CLAIMS_BLOCK)
    parts.append(FIGURES_BLOCK)
    text = "\n".join(parts)
    check_rule_13(text)
    TTL_OUT.write_text(text)

    import rdflib
    g = rdflib.Graph()
    g.parse(TTL_OUT, format="turtle")
    print(f"OK: wrote {TTL_OUT.relative_to(REPO)} "
          f"({len(g)} triples, {len(set(g.subjects()))} subjects)")
    print(f"  sources modelled: {len(sources)}")
    print(f"  run instances:    {len(runs)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
