#!/usr/bin/env python3
"""Build a static, browser-viewable visualisation of `docs/provenance.ttl`.

Loads the PROV-O Turtle graph, projects it to Cytoscape.js elements,
and writes:

    docs/site/index.html   - viewer (Cytoscape.js via CDN; offline-capable
                             once the CDN bundle is cached by the browser)
    docs/site/graph.json   - the elements (nodes + edges) the viewer reads
    docs/site/style.css    - minimal layout + filter-chip styles
    docs/site/README.md    - rule-14 / rule-13 note

The viewer supports:
    - class filter (Claim / Source / Activity / Agent / Figure / Build / Commit)
    - verification-rung filter (lit-read / ai-confirmed / lit-retrieved / ...)
    - click-to-inspect (full triple list for the clicked entity)
    - search by label

Rule 14: deployment of THIS site (the provenance-graph viewer) to GitHub
Pages was explicitly consented to by the human author (Florian Krebs)
on 2026-05-04 — see docs/logbook.md (Q14 entry) for the consent record
and .github/workflows/pages.yml for the deploy workflow. Consent does
not extend to other rule-14 gates: public-mirror push of the full
repository, Zenodo deposit, and arXiv submission each require their
own explicit consent.

Rule 13: redacted markers in the graph are passed through verbatim;
no live values are looked up. The script also refuses to write the site
if any node label or comment matches a known live-credential pattern.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import rdflib
from rdflib import RDF, RDFS, Graph, URIRef
from rdflib.namespace import DCTERMS, FOAF, XSD


REPO_ROOT = Path(__file__).resolve().parent.parent
TTL_IN = REPO_ROOT / "docs" / "provenance.ttl"
SITE_DIR = REPO_ROOT / "docs" / "site"

PROV = rdflib.Namespace("http://www.w3.org/ns/prov#")
OID = rdflib.Namespace("https://github.com/noheton/obscurity-is-dead/ns#")

CLASS_PALETTE = {
    "Claim":              {"color": "#1f6feb", "shape": "round-rectangle"},
    "Source":             {"color": "#8957e5", "shape": "ellipse"},
    "Transcript":         {"color": "#bf8700", "shape": "diamond"},
    "Figure":             {"color": "#1a7f37", "shape": "round-tag"},
    "Commit":             {"color": "#6e7781", "shape": "round-hexagon"},
    "VerificationStatus": {"color": "#cf222e", "shape": "round-pentagon"},
    "PipelineStage":      {"color": "#0969da", "shape": "round-octagon"},
    "Build":              {"color": "#116329", "shape": "round-diamond"},
    "AIAgent":            {"color": "#9a6700", "shape": "rectangle"},
    "HumanResearcher":    {"color": "#cf222e", "shape": "rectangle"},
    "Agent":              {"color": "#bf8700", "shape": "rectangle"},
    "Entity":             {"color": "#57606a", "shape": "ellipse"},
    "Activity":           {"color": "#0969da", "shape": "round-octagon"},
}

EDGE_PALETTE = {
    "wasDerivedFrom":   {"color": "#1f6feb", "label": "derived from"},
    "wasGeneratedBy":   {"color": "#1a7f37", "label": "generated by"},
    "wasAttributedTo":  {"color": "#8957e5", "label": "attributed to"},
    "used":             {"color": "#bf8700", "label": "used"},
    "wasAssociatedWith":{"color": "#0969da", "label": "associated with"},
    "wasInformedBy":    {"color": "#6e7781", "label": "informed by"},
    "generated":        {"color": "#1a7f37", "label": "generated"},
    "hasVerificationStatus": {"color": "#cf222e", "label": "verification"},
}

# Rule-13 sentinel patterns. The graph must NEVER carry a live credential
# in any literal. These are conservative regexps; matching means refuse.
LIVE_CREDENTIAL_PATTERNS = [
    re.compile(r"AKIA[0-9A-Z]{16}"),               # AWS access key
    re.compile(r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}"),  # JWT
    re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"),   # Slack tokens
    re.compile(r"ghp_[A-Za-z0-9]{30,}"),           # GitHub PAT
]


def short(uri: str) -> str:
    if uri.startswith(str(OID)):
        return "oid:" + uri[len(str(OID)):]
    if uri.startswith(str(PROV)):
        return "prov:" + uri[len(str(PROV)):]
    if uri.startswith(str(DCTERMS)):
        return "dct:" + uri[len(str(DCTERMS)):]
    if uri.startswith(str(RDFS)):
        return "rdfs:" + uri[len(str(RDFS)):]
    if uri.startswith(str(FOAF)):
        return "foaf:" + uri[len(str(FOAF)):]
    return uri


def class_label_for(types: set[URIRef]) -> str:
    candidates = [short(str(t)).removeprefix("oid:").removeprefix("prov:")
                  for t in types]
    # Prefer the most specific local class.
    priority = ["Claim", "Source", "Transcript", "Figure", "Commit",
                "VerificationStatus", "Build", "PipelineStage",
                "AIAgent", "HumanResearcher", "Agent", "Activity", "Entity"]
    for p in priority:
        if p in candidates:
            return p
    return candidates[0] if candidates else "Entity"


def collect_nodes(g: Graph) -> dict[str, dict]:
    nodes: dict[str, dict] = {}
    for s in set(g.subjects()):
        if not isinstance(s, URIRef):
            continue
        types = set(g.objects(s, RDF.type))
        if not types and not any(g.predicate_objects(s)):
            continue
        cls = class_label_for(types) if types else "Entity"
        title = (g.value(s, DCTERMS.title)
                 or g.value(s, FOAF.name)
                 or g.value(s, RDFS.label)
                 or g.value(s, DCTERMS.identifier))
        comment = g.value(s, RDFS.comment) or g.value(s, DCTERMS.description)
        verification = g.value(s, OID.hasVerificationStatus)
        triples = []
        for p, o in g.predicate_objects(s):
            triples.append({"p": short(str(p)), "o": str(o),
                            "is_uri": isinstance(o, URIRef)})
        nodes[str(s)] = {
            "id": str(s),
            "short": short(str(s)),
            "class": cls,
            "title": str(title) if title else short(str(s)),
            "comment": str(comment) if comment else "",
            "verification": short(str(verification)) if verification else "",
            "types": [short(str(t)) for t in types],
            "triples": triples,
        }
    return nodes


def collect_edges(g: Graph, nodes: dict[str, dict]) -> list[dict]:
    edges: list[dict] = []
    edge_predicates = {
        PROV.wasDerivedFrom, PROV.wasGeneratedBy, PROV.wasAttributedTo,
        PROV.used, PROV.wasAssociatedWith, PROV.wasInformedBy,
        PROV.generated, OID.hasVerificationStatus,
    }
    for s, p, o in g:
        if p not in edge_predicates:
            continue
        if not isinstance(s, URIRef) or not isinstance(o, URIRef):
            continue
        if str(s) not in nodes or str(o) not in nodes:
            continue
        pred_local = short(str(p)).split(":", 1)[-1]
        edges.append({
            "id": f"{s}--{pred_local}--{o}",
            "source": str(s),
            "target": str(o),
            "predicate": pred_local,
        })
    return edges


def check_rule_13(nodes: dict[str, dict]) -> None:
    leaks: list[tuple[str, str]] = []
    for nid, node in nodes.items():
        haystacks = [node["title"], node["comment"]]
        haystacks.extend(t["o"] for t in node["triples"])
        for hay in haystacks:
            for pattern in LIVE_CREDENTIAL_PATTERNS:
                if pattern.search(hay):
                    leaks.append((nid, pattern.pattern))
    if leaks:
        print("RULE-13 GUARD: refusing to write site; live-credential pattern detected.",
              file=sys.stderr)
        for nid, pat in leaks:
            print(f"  {nid}: {pat}", file=sys.stderr)
        sys.exit(2)


def write_graph_json(nodes: dict[str, dict], edges: list[dict]) -> dict:
    elements = {
        "nodes": [
            {"data": {
                "id": n["id"],
                "short": n["short"],
                "label": n["title"],
                "cls": n["class"],
                "comment": n["comment"],
                "verification": n["verification"],
                "types": n["types"],
                "triples": n["triples"],
            }} for n in nodes.values()
        ],
        "edges": [
            {"data": {
                "id": e["id"],
                "source": e["source"],
                "target": e["target"],
                "label": EDGE_PALETTE.get(e["predicate"], {}).get("label", e["predicate"]),
                "predicate": e["predicate"],
            }} for e in edges
        ],
    }
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    out = SITE_DIR / "graph.json"
    out.write_text(json.dumps(elements, indent=2, ensure_ascii=False))
    return elements


def write_html(elements: dict, source_sha: str) -> None:
    classes = sorted({n["data"]["cls"] for n in elements["nodes"]})
    rungs = sorted({n["data"]["verification"]
                    for n in elements["nodes"]
                    if n["data"]["verification"]})
    class_palette_js = json.dumps(CLASS_PALETTE)
    edge_palette_js = json.dumps(EDGE_PALETTE)

    chips_classes = "\n".join(
        f'<label class="chip"><input type="checkbox" data-class="{c}" checked> '
        f'<span class="swatch" style="background:{CLASS_PALETTE.get(c, {}).get("color", "#888")}"></span>{c}</label>'
        for c in classes
    )
    chips_rungs = "\n".join(
        f'<label class="chip"><input type="checkbox" data-rung="{r}" checked>{r}</label>'
        for r in rungs
    ) or '<span class="muted">no rungs in current bootstrap</span>'

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Obscurity Is Dead — Provenance Graph (PROV-O)</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="style.css">
<script src="https://unpkg.com/cytoscape@3.30.4/dist/cytoscape.min.js"></script>
<script src="https://unpkg.com/cytoscape-cose-bilkent@4.1.0/cytoscape-cose-bilkent.js"></script>
</head>
<body>
<header>
  <div class="title">
    <h1>Obscurity Is Dead — Provenance Graph</h1>
    <p>W3C PROV-O rendering of <code>docs/provenance.ttl</code>
    (regenerated by <code>scripts/build_provenance_graph.py</code>;
    rendered to this viewer by <code>scripts/build_provenance_site.py</code>;
    source SHA <code>{source_sha}</code>).
    <strong>Rule 14:</strong> the human author (Florian Krebs) has given
    explicit written consent for this site to be deployed to GitHub Pages
    (recorded in <code>docs/logbook.md</code>, 2026-05-04 Q14 entry).
    Consent applies to the provenance-graph viewer only; public-mirror push
    of the full repository, Zenodo deposit, and arXiv submission remain
    separate consent gates.</p>
  </div>
</header>

<aside id="controls">
  <h2>Filter by class</h2>
  <div class="chips">{chips_classes}</div>
  <h2>Filter by verification rung</h2>
  <div class="chips">{chips_rungs}</div>
  <h2>Search</h2>
  <input id="search" type="search" placeholder="title, identifier, comment…" autocomplete="off">
  <h2>Layout</h2>
  <select id="layout">
    <option value="cose-bilkent" selected>force-directed (cose-bilkent)</option>
    <option value="breadthfirst">breadth-first</option>
    <option value="concentric">concentric</option>
    <option value="circle">circle</option>
    <option value="grid">grid</option>
  </select>
  <button id="fit">Fit to view</button>
  <h2>Stats</h2>
  <p id="stats" class="muted"></p>
</aside>

<main id="cy"></main>

<aside id="inspector">
  <h2>Click a node</h2>
  <div id="inspector-body"><p class="muted">No selection.</p></div>
</aside>

<footer>
  <span><a href="../provenance.ttl">Source: <code>docs/provenance.ttl</code></a></span>
  <span><a href="../prompts/modeler-prompt.md">Modeler agent (stage 7)</a></span>
  <span><a href="../handbacks/modeler-report.md">Last run report</a></span>
  <span><a href="../../paper/main.md">Long-form paper</a></span>
  <span><a href="../../CLAUDE.md">CLAUDE.md (rules &amp; agent workflow)</a></span>
</footer>

<script>
const CLASS_PALETTE = {class_palette_js};
const EDGE_PALETTE  = {edge_palette_js};

fetch('graph.json').then(r => r.json()).then(start);

function start(elements) {{
  const styleNodes = Object.entries(CLASS_PALETTE).map(([cls, p]) => ({{
    selector: `node[cls = "${{cls}}"]`,
    style: {{
      'background-color': p.color,
      'shape': p.shape,
      'border-color': '#1f2328',
      'border-width': 1,
      'label': 'data(short)',
      'color': '#1f2328',
      'font-size': 9,
      'text-wrap': 'wrap',
      'text-max-width': 110,
      'text-valign': 'center',
      'text-halign': 'center',
      'width': 'label',
      'height': 'label',
      'padding': '6px',
    }},
  }}));
  const styleEdges = Object.entries(EDGE_PALETTE).map(([pred, p]) => ({{
    selector: `edge[predicate = "${{pred}}"]`,
    style: {{
      'line-color': p.color,
      'target-arrow-color': p.color,
      'target-arrow-shape': 'triangle',
      'curve-style': 'bezier',
      'width': 1,
      'opacity': 0.8,
      'label': '',
    }},
  }}));

  const cy = cytoscape({{
    container: document.getElementById('cy'),
    elements,
    minZoom: 0.2,
    maxZoom: 3,
    wheelSensitivity: 0.25,
    style: [
      ...styleNodes,
      ...styleEdges,
      {{ selector: 'node:selected', style: {{
        'border-width': 3,
        'border-color': '#cf222e',
      }} }},
      {{ selector: 'edge:selected', style: {{ 'width': 3 }} }},
      {{ selector: '.dim', style: {{ 'opacity': 0.1 }} }},
      {{ selector: '.hilite', style: {{ 'opacity': 1 }} }},
    ],
    layout: {{ name: 'cose-bilkent', animate: false, idealEdgeLength: 90,
              nodeRepulsion: 9000, gravity: 0.25 }},
  }});

  document.getElementById('stats').textContent =
    `${{cy.nodes().length}} nodes · ${{cy.edges().length}} edges`;

  cy.on('tap', 'node', evt => render(evt.target.data()));

  function render(d) {{
    const body = document.getElementById('inspector-body');
    const tripleRows = (d.triples || []).map(t =>
      `<tr><td class="pred">${{escapeHtml(t.p)}}</td><td>${{
        t.is_uri
          ? `<code>${{escapeHtml(t.o)}}</code>`
          : escapeHtml(t.o)
      }}</td></tr>`).join('');
    body.innerHTML = `
      <h3>${{escapeHtml(d.label || d.short)}}</h3>
      <p class="muted"><code>${{escapeHtml(d.short)}}</code></p>
      <p class="muted">Class: <strong>${{escapeHtml(d.cls)}}</strong>${{
        d.verification ? ` · ${{escapeHtml(d.verification)}}` : ''
      }}</p>
      ${{d.comment ? `<p>${{escapeHtml(d.comment)}}</p>` : ''}}
      <table class="triples">${{tripleRows}}</table>
    `;
  }}

  function applyFilters() {{
    const enabledClasses = new Set(
      [...document.querySelectorAll('input[data-class]:checked')]
        .map(i => i.dataset.class));
    const enabledRungs = new Set(
      [...document.querySelectorAll('input[data-rung]:checked')]
        .map(i => i.dataset.rung));
    const q = document.getElementById('search').value.trim().toLowerCase();
    cy.batch(() => {{
      cy.nodes().forEach(n => {{
        const d = n.data();
        let show = enabledClasses.has(d.cls);
        if (show && d.verification && enabledRungs.size) {{
          show = enabledRungs.has(d.verification);
        }}
        if (show && q) {{
          const hay = (d.label + ' ' + d.short + ' ' + (d.comment || '')).toLowerCase();
          show = hay.includes(q);
        }}
        n.style('display', show ? 'element' : 'none');
      }});
      cy.edges().forEach(e => {{
        const visible = e.source().style('display') !== 'none'
                     && e.target().style('display') !== 'none';
        e.style('display', visible ? 'element' : 'none');
      }});
    }});
  }}

  document.querySelectorAll('input[data-class], input[data-rung]')
    .forEach(i => i.addEventListener('change', applyFilters));
  document.getElementById('search').addEventListener('input', applyFilters);
  document.getElementById('layout').addEventListener('change', e => {{
    cy.layout({{ name: e.target.value, animate: false }}).run();
  }});
  document.getElementById('fit').addEventListener('click', () => cy.fit(null, 30));
}}

function escapeHtml(s) {{
  return String(s).replace(/[&<>"']/g, c => ({{
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }}[c]));
}}
</script>
</body>
</html>
"""
    (SITE_DIR / "index.html").write_text(html)


CSS = """\
* { box-sizing: border-box; }
html, body { margin: 0; height: 100%; font-family: -apple-system, "SF Pro Text", system-ui, sans-serif; color: #1f2328; background: #f6f8fa; }
body { display: grid; grid-template-rows: auto 1fr auto; grid-template-columns: 280px 1fr 320px; grid-template-areas: "header header header" "controls graph inspector" "footer footer footer"; height: 100vh; }
header { grid-area: header; padding: 14px 20px; background: #1f2328; color: #f6f8fa; }
header h1 { margin: 0 0 4px 0; font-size: 18px; }
header p { margin: 0; font-size: 12px; color: #c9d1d9; max-width: 100ch; }
header code { background: #2d333b; padding: 1px 4px; border-radius: 3px; font-size: 11px; }
header strong { color: #ffd33d; }
#controls { grid-area: controls; padding: 14px; overflow: auto; border-right: 1px solid #d0d7de; background: #fff; }
#controls h2 { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #57606a; margin: 16px 0 6px; }
#controls h2:first-child { margin-top: 0; }
.chips { display: flex; flex-wrap: wrap; gap: 4px; }
.chip { display: inline-flex; align-items: center; gap: 4px; font-size: 11px; padding: 3px 7px; border: 1px solid #d0d7de; border-radius: 999px; background: #f6f8fa; cursor: pointer; }
.chip input { margin: 0; }
.swatch { width: 9px; height: 9px; border-radius: 50%; display: inline-block; border: 1px solid #1f232844; }
#search, #layout { width: 100%; padding: 5px 8px; border: 1px solid #d0d7de; border-radius: 6px; font-size: 12px; }
#fit { margin-top: 8px; padding: 5px 10px; border: 1px solid #d0d7de; background: #f6f8fa; border-radius: 6px; cursor: pointer; font-size: 12px; }
#fit:hover { background: #eaeef2; }
.muted { color: #57606a; font-size: 11px; }
#cy { grid-area: graph; background: #fff; }
#inspector { grid-area: inspector; padding: 14px; overflow: auto; border-left: 1px solid #d0d7de; background: #fff; font-size: 12px; }
#inspector h2 { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #57606a; margin: 0 0 8px; }
#inspector h3 { margin: 0 0 4px; font-size: 14px; }
.triples { width: 100%; border-collapse: collapse; font-size: 11px; margin-top: 8px; }
.triples td { padding: 4px 6px; border-top: 1px solid #eaeef2; vertical-align: top; word-break: break-word; }
.triples td.pred { width: 38%; color: #57606a; }
.triples code { font-size: 10px; background: #f6f8fa; padding: 1px 3px; border-radius: 3px; }
footer { grid-area: footer; padding: 8px 16px; background: #f6f8fa; border-top: 1px solid #d0d7de; font-size: 11px; display: flex; gap: 16px; flex-wrap: wrap; }
footer a { color: #0969da; text-decoration: none; }
footer a:hover { text-decoration: underline; }
"""


SITE_README = """\
# Obscurity Is Dead — provenance graph viewer

This directory holds a static, browser-viewable rendering of
`../provenance.ttl` (the W3C PROV-O graph emitted by the Modeler agent,
stage 7 — see `../prompts/modeler-prompt.md`). The graph itself is
regenerated by `scripts/build_provenance_graph.py`; this viewer is
regenerated from the graph by `scripts/build_provenance_site.py`. The
GitHub Actions workflow at `.github/workflows/pages.yml` runs both on
every push to `main` and deploys the result to GitHub Pages.

- **Rule 14 (CLAUDE.md):** deployment of THIS site (the
  provenance-graph viewer) to GitHub Pages was explicitly consented to
  by the human author (Florian Krebs) on 2026-05-04 — recorded in
  `../logbook.md` (Q14 entry). Consent applies to the provenance-graph
  viewer only; public-mirror push of the full repository, Zenodo
  deposit, and arXiv submission remain separate consent gates.
- **Rule 13 (CLAUDE.md):** both the graph build and the site build
  refuse to write their outputs if any literal matches a known
  live-credential pattern. Redaction markers (`[REDACTED:...]`) pass
  through verbatim.

## Build

```
pip install rdflib
python3 scripts/build_provenance_graph.py    # regenerates docs/provenance.ttl
python3 scripts/build_provenance_site.py     # regenerates docs/site/
```

Then open `docs/site/index.html` in a browser, or visit the deployed
GitHub Pages URL configured by `.github/workflows/pages.yml`. Cytoscape.js is loaded
from a CDN; the file works offline once the bundle is cached, or can be
made hermetic by vendoring `cytoscape.min.js` and
`cytoscape-cose-bilkent.js` next to `index.html`.

## What you see

- **Nodes** — every `prov:Entity` / `prov:Activity` / `prov:Agent`
  in the graph, coloured by class (Claim / Source / Activity / Agent /
  Figure / Build / Commit / VerificationStatus).
- **Edges** — `prov:wasDerivedFrom`, `prov:wasGeneratedBy`,
  `prov:wasAttributedTo`, `prov:used`, `prov:wasAssociatedWith`,
  `prov:wasInformedBy`, `prov:generated`, `oid:hasVerificationStatus`.
- **Filters** — class chips, verification-rung chips, free-text search.
- **Inspector** — click a node to see its full triple list.

## Companion / canonical artifacts

- The Turtle source: `../provenance.ttl`.
- The Modeler agent prompt: `../prompts/modeler-prompt.md`.
- The Modeler run report (per-pass): `../handbacks/modeler-report.md`.
- The paper that the graph models: `../../paper/main.md`,
  `../../paper/main-condensed.md`.
- The rules the graph encodes: `../../CLAUDE.md` (esp. rules 13, 14, 18).
"""


def main() -> int:
    if not TTL_IN.exists():
        print(f"error: {TTL_IN} does not exist", file=sys.stderr)
        return 1
    g = Graph()
    g.parse(TTL_IN, format="turtle")
    nodes = collect_nodes(g)
    edges = collect_edges(g, nodes)
    check_rule_13(nodes)
    elements = write_graph_json(nodes, edges)
    import subprocess
    sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                         capture_output=True, text=True, cwd=REPO_ROOT).stdout.strip() or "(no git)"
    write_html(elements, sha)
    (SITE_DIR / "style.css").write_text(CSS)
    (SITE_DIR / "README.md").write_text(SITE_README)
    print(f"OK: wrote {SITE_DIR}/index.html "
          f"({len(elements['nodes'])} nodes, {len(elements['edges'])} edges)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
